# Generated by Django 5.1.1 on 2024-09-26 13:01

import django.db.models.deletion
import encrypted_model_fields.fields
import user.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', encrypted_model_fields.fields.EncryptedCharField(unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('first_name', encrypted_model_fields.fields.EncryptedCharField(null=True)),
                ('last_name', encrypted_model_fields.fields.EncryptedCharField(null=True)),
                ('user_type', models.SmallIntegerField(blank=True, choices=[(1, 'ADMIN'), (2, 'RECRUITER'), (3, 'JOB_SEEKER')], null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_client', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', user.managers.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='job_seeker', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('education', models.JSONField(blank=True, default=list)),
                ('skills', models.TextField(blank=True)),
                ('experience', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='recruiter', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', encrypted_model_fields.fields.EncryptedCharField()),
            ],
        ),
    ]
